import type { EfetivoRow } from './types'

export const demoRows: EfetivoRow[] = [
  {
    opm: 'CPE',
    grauHierarquico: 'TEN CEL',
    quadro: 'QOPM',
    funcao: 'Comando',
    caracteristicaDaFuncao: 'Atividade Meio',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'Comando',
  },
  {
    opm: 'CPE',
    grauHierarquico: 'MAJ',
    quadro: 'QOPM',
    funcao: 'P3',
    caracteristicaDaFuncao: 'Atividade Meio',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'P3',
  },
  {
    opm: 'CPE',
    grauHierarquico: 'SGT',
    quadro: 'QPPM',
    funcao: 'P1',
    caracteristicaDaFuncao: 'Atividade Meio',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'P1',
  },
  {
    opm: 'CPE',
    grauHierarquico: 'CB',
    quadro: 'QPPM',
    funcao: 'Operações',
    caracteristicaDaFuncao: 'Atividade Fim',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'Operações',
  },
  {
    opm: 'BPVE',
    grauHierarquico: 'TEN CEL',
    quadro: 'QOPM',
    funcao: 'Comando',
    caracteristicaDaFuncao: 'Atividade Meio',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'Comando',
  },
  {
    opm: 'BPVE',
    grauHierarquico: 'MAJ',
    quadro: 'QOPM',
    funcao: 'Operações',
    caracteristicaDaFuncao: 'Atividade Fim',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'Operações',
  },
  {
    opm: 'BPVE',
    grauHierarquico: 'CAP',
    quadro: 'QOPM',
    funcao: 'Operações',
    caracteristicaDaFuncao: 'Atividade Fim',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'Operações',
  },
  {
    opm: 'BEP',
    grauHierarquico: 'TEN',
    quadro: 'QOPM',
    funcao: 'Operações',
    caracteristicaDaFuncao: 'Atividade Fim',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'Operações',
  },
  {
    opm: 'BEP',
    grauHierarquico: 'SUBTEN',
    quadro: 'QPPM',
    funcao: 'P1',
    caracteristicaDaFuncao: 'Atividade Meio',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'P1',
  },
  {
    opm: 'BPTUR',
    grauHierarquico: 'SGT',
    quadro: 'QPPM',
    funcao: 'Turismo',
    caracteristicaDaFuncao: 'Atividade Fim',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'Turismo',
  },
  {
    opm: 'BPTUR',
    grauHierarquico: 'CB',
    quadro: 'QPPM',
    funcao: 'Turismo',
    caracteristicaDaFuncao: 'Atividade Fim',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'Turismo',
  },
  {
    opm: 'BPTUR',
    grauHierarquico: 'SD',
    quadro: 'QPPM',
    funcao: 'Turismo',
    caracteristicaDaFuncao: 'Atividade Fim',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'Turismo',
  },
  {
    opm: 'GPFER',
    grauHierarquico: 'SD',
    quadro: 'QPPM',
    funcao: 'P4',
    caracteristicaDaFuncao: 'Atividade Meio',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'P4',
  },
  {
    opm: 'RPMONT',
    grauHierarquico: 'CB',
    quadro: 'QPPM',
    funcao: 'Cavalaria',
    caracteristicaDaFuncao: 'Atividade Fim',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'Cavalaria',
  },
  {
    opm: '1ª CIPM',
    grauHierarquico: 'SGT',
    quadro: 'QPPM',
    funcao: 'Trânsito',
    caracteristicaDaFuncao: 'Atividade Fim',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'Trânsito',
  },
  {
    opm: '1ª CIPM',
    grauHierarquico: 'TEN',
    quadro: 'QOPM',
    funcao: 'Administração',
    caracteristicaDaFuncao: 'Atividade Meio',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'Administração',
  },
  {
    opm: 'RECOM',
    grauHierarquico: 'CAP',
    quadro: 'QOPM',
    funcao: 'Operações',
    caracteristicaDaFuncao: 'Atividade Fim',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'Operações',
  },
  {
    opm: 'RECOM',
    grauHierarquico: 'SD',
    quadro: 'QPPM',
    funcao: 'P4',
    caracteristicaDaFuncao: 'Atividade Meio',
    situacaoGeral: 'ATIVO',
    setorOuSecao: 'P4',
  },
]
